In [ ]:
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from kagglehub.datasets import dataset_download
import kagglehub
from google.colab import userdata

KAGGLE_API_KEY = userdata.get('KAGGLE_API_KEY')

#Downloading using kagglehub.dataset_download
dataset_handle = "yash9439/ipl-dataset"
path = kagglehub.dataset_download(dataset_handle)

print(f"Path to dataset files: {path}")

#1. First dataset cleaning

In [ ]:
# import_dataset
dataset = pd.read_csv(f"/kaggle/input/ipl-dataset/deliveries.csv")

In [ ]:
#5_records_of_the_dataset_deliveries
dataset.head(9)

In [ ]:
#Rows_columns_and_datatypes_in_dataset_using_pd.info()
dataset.info()

In [ ]:
#Let_us_know_how_many_NaN_features_we_have
display(dataset.isnull().sum())

we_need_to_address_these_three_features
player_dismissed	143022
dismissal_kind	143022
fielder	145091

In [ ]:
#Let_us_use_pd.describe_function
display(dataset.describe())

In [ ]:
dataset.columns

In [ ]:
#Top10_bowler_that_gave_least_run
#Top10_bowler_that_gave_most_run
#Top_10_batsmen_who_scored_most_run
#Top_10_who_scored_least_run
#Most_wide_bowler
# most_no_balls_player
#Most_wide_ball_player_
#Most_dismissals
#All_matchups
#Super_over_max_runs.
#teams_who_gave_most_extra_runs
#most_wicket_by_dismissal_kind
#player_who_dismissed_the_most
#fielder_who_caught_more
#most_player_dismissed_againet_which_team
# which_team_bowled_good,percent_wise_pie_chart

In [ ]:
delivery_dataset = dataset.copy()

In [ ]:
numerical_columns = [feature for feature in delivery_dataset.columns if dataset[feature].dtype != 'object' and feature not in ['match_id','inning']]
display(numerical_columns)

categorical_columns = [feature for feature in delivery_dataset.columns if dataset[feature].dtype == 'object' and feature not in ['match_id','inning']]
print()
display(categorical_columns)

In [ ]:
#Using dataset.melts fro visualising multiple numerical columns using box plot.
melted_data_before_capping = delivery_dataset.melt(
                    value_vars= numerical_columns,var_name='Numerical Feature',
                    value_name='Value')

#Create a sigle figure with subplots for each box plot.
plt.figure(figsize=(15,10))
sea.boxplot(x='Numerical Feature',y='Value', hue='Numerical Feature',
            data=melted_data_before_capping,palette='viridis', legend=False)
plt.title("Box Plot of All Numerical Features")
plt.xlabel('Numerical Features')
plt.ylabel("Value")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"i" decided to keep the dataset with outliers because you found that the capping process "ruined the data." In the context of cricket, what might appear as a statistical outlier can often be a meaningful and crucial data point, and you preferred to retain the original distribution and its contextual significance.

In [ ]:
# player_dismissed	143022
# dismissal_kind	143022
# fielder	145091

delivery_dataset['player_dismissed']= delivery_dataset['player_dismissed'].fillna("not out")

delivery_dataset['dismissal_kind'] = delivery_dataset['dismissal_kind'].fillna("N/A")

delivery_dataset['fielder'] = delivery_dataset['fielder'].fillna("N/A")

In [ ]:
delivery_dataset.isnull().sum()

In [ ]:
print(f"Number of duplicate rows: {delivery_dataset.duplicated().sum()}")

In [ ]:
delivery_dataset.drop_duplicates(inplace=True)

In [ ]:
print(f"Number of duplicate rows after dropping: {delivery_dataset.duplicated().sum()}")

In [ ]:
print("Dataset after cleaning:")
display(delivery_dataset.head())

As my datset is cleaned now i will start plotting graphs..

In [ ]:
display(f"The dataset has these columns: {dataset.columns}")

In [ ]:
all_teams = np.unique(delivery_dataset[['batting_team']])
print("Teams Before Standardising names: ",len(all_teams))
display(all_teams)

In [ ]:
same_team_name = {
                  'Rising Pune Supergiants' : 'Rising Pune Supergiant',
                  'Delhi Daredevils':'Delhi Capitals',
                  'Deccan Chargers':'Sunrisers Hyderabad',
                  'Kings XI Punjab':"Punjab Kings"
}

def standardised_team_name(df,columns):
  for col in columns:
    df[col] = df[col].replace(same_team_name)
  return df

team_columns= ['batting_team', 'bowling_team']
delivery_dataset = standardised_team_name(delivery_dataset,team_columns)

In [ ]:
all_teams = np.unique(delivery_dataset[['batting_team']])
print("Teams After Standardising names: ",len(all_teams))
display(all_teams)

In [ ]:
dataset['match_id'].nunique()

In [ ]:
print("Top 10 Batsmen who faced the most balls:")
top_10_most_ball_faced_batsman = delivery_dataset['batsman'].value_counts().head(10)
display(delivery_dataset['batsman'].value_counts().head(10))
plt.figure(figsize=(10,8))
sea.barplot(x=top_10_most_ball_faced_batsman.values,
           y=top_10_most_ball_faced_batsman.index,)
plt.title("Top 10 Batsmen who faced the most balls:")
plt.xlabel("Balls Faced")
plt.ylabel("Batsmen")
plt.show()

print("Top 10 Bowler who bowled most balls: ")
top_10_most_bowled_baller = delivery_dataset['bowler'].value_counts().head(10)
display(top_10_most_bowled_baller)
plt.figure(figsize=(10,8))
sea.barplot(x=top_10_most_bowled_baller.values,
           y=top_10_most_bowled_baller.index,)
plt.title("Top 10 Bowler who bowled most balls: ")
plt.xlabel("Balls Bowled")
plt.ylabel("Bowlers")

plt.show()

In [ ]:
top_scoring_batsmen = delivery_dataset.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False)
display(top_scoring_batsmen.head(10))

top_10_most_dismissed_players = delivery_dataset['player_dismissed'].value_counts().head(11)
display(top_10_most_dismissed_players)

In [ ]:
#bowler_who_gave_most_runs
most_run_giving_bowler = delivery_dataset.groupby('bowler')['total_runs'].sum().sort_values(ascending=False)
display(most_run_giving_bowler)

In [ ]:
bowler_who_bowled_most_wide = delivery_dataset.groupby('bowler')['wide_runs'].sum().sort_values(ascending=False)
# display(bowler_who_bowled_most_wide)

bowler_who_bowled_most_no_balls = delivery_dataset.groupby('bowler')['noball_runs'].sum().sort_values(ascending=False).head(10)
# display(bowler_who_bowled_most_no_balls)

bowlers_who_bowled_most_bye_runs = delivery_dataset.groupby('bowler')['bye_runs'].sum().sort_values(ascending=False).head(10)
# display(bowlers_who_bowled_most_bye_runs)

bowlers_who_bowled_most_legbye_runs = delivery_dataset.groupby('bowler')['legbye_runs'].sum().sort_values(ascending=False).head(10)
# display(bowlers_who_bowled_most_legbye_runs)

bowler_who_bowled_most_penalty_runs = delivery_dataset.groupby('bowler')['penalty_runs'].sum().sort_values(ascending=False).head(10)
# display(bowler_who_bowled_most_penalty_runs)

bowler_who_bowled_extra_runs_overall = delivery_dataset.groupby('bowler')['extra_runs'].sum().sort_values(ascending=False).head(10)
display(bowler_who_bowled_extra_runs_overall)

In [ ]:
all_matchups = dataset[['batting_team','bowling_team']].value_counts().reset_index()
# all_matchups.value_counts()
all_matchups

In [ ]:
dismissal_kinds_fequency = delivery_dataset['dismissal_kind'].value_counts().sort_values(ascending=False)

# Filter out 'N/A' to focus on actual dismissal kinds for visualization
dismissal_kinds_for_plot = dismissal_kinds_fequency[dismissal_kinds_fequency.index != 'N/A']

plt.figure(figsize=(10, 7))
sea.barplot(x=dismissal_kinds_for_plot.values, y=dismissal_kinds_for_plot.index, palette='viridis',hue=dismissal_kinds_for_plot.values,legend=False)
plt.title('Frequency of Dismissal Kinds (Excluding Not Out)')
plt.xlabel('Count')
plt.ylabel('Dismissal Kind')
plt.tight_layout()
plt.show()

In [ ]:
fielder_who_caught_most_balls = delivery_dataset['fielder'].value_counts().head(10)
fielder_who_caught_most_balls_plot =fielder_who_caught_most_balls[fielder_who_caught_most_balls.index!='N/A']
display(fielder_who_caught_most_balls_plot)

In [ ]:
teams_and_extra_runs = delivery_dataset.groupby('bowling_team')['extra_runs'].sum().sort_values(ascending=False).head(12)
idisplay(teams_and_extra_runs)

In [ ]:
# Filter for dismissal kinds where the bowler is credited
bowler_credited_dismissals = delivery_dataset[
    delivery_dataset['dismissal_kind'].isin(['caught', 'bowled', 'lbw', 'stumped', 'caught and bowled'])
]

# Group by bowler and count the dismissals, then sort
wickets_by_bowler = bowler_credited_dismissals.groupby('bowler')['dismissal_kind'].count().sort_values(ascending=False)
wickets_by_bowler= wickets_by_bowler.reset_index()
wickets_by_bowler.rename(columns={'dismissal_kind':'no.of_wickets'},inplace=True)
udisplay(wickets_by_bowler.head(10)) # Displaying top 10 wicket-takers

In [ ]:
#Run conceded by each bowler
bowler_total_runs = delivery_dataset.groupby('bowler')['total_runs'].sum().reset_index()

bowler_total_runs.rename(columns={'total_runs':'runs_conceded'},inplace=True)

#Merge with wickets_by_bowler dataframe
bowler_stats = pd.merge(bowler_total_runs,wickets_by_bowler,on='bowler',how='left')
bowler_stats['no.of_wickets'] = bowler_stats['no.of_wickets'].fillna(0)

# Vectorized bowling average calculation
# Handle division by zero by replacing 0 with NaN, then filling NaN with inf after division
bowler_stats['bowling_average'] = bowler_stats['runs_conceded'] / bowler_stats['no.of_wickets'].replace(0, np.nan)
bowler_stats['bowling_average'] = bowler_stats['bowling_average'].fillna(np.inf)

display(bowler_stats.sort_values(by=['bowling_average']).head(30))

In [ ]:
display(bowler_stats.sort_values(by='no.of_wickets', ascending=False).head(10))

In [ ]:
# batsmen_total_runs = top_scoring_batsmen.copy()
# batsman_total_balls = delivery_dataset['batsman'].value_counts().reset_index()

# batsman_total_balls.rename(columns={'count':'no.of_balls'},inplace=True)
# display(batsmen_total_runs)

# batsmen_stats = pd.merge(batsmen_total_runs,batsman_total_balls,on='batsman',how='left')

# display(batsmen_stats,batsmen_stats.isnull().sum())
# batsmen_stats['strike_rate']= batsmen_stats.apply(lambda row: (row['batsman_runs']/row['no.of_balls'])*100 if row['no.of_balls'] > 0 else np.inf, axis=1)

In [61]:
batsmen_total_runs = top_scoring_batsmen.copy()
batsman_total_balls = delivery_dataset['batsman'].value_counts().reset_index()

batsman_total_balls.rename(columns={'count':'no.of_balls'},inplace=True)
display(batsmen_total_runs)

batsmen_stats = pd.merge(batsmen_total_runs,batsman_total_balls,on='batsman',how='left')

display(batsmen_stats,batsmen_stats.isnull().sum())

# Vectorized strike rate calculation
# Handle division by zero by replacing 0 with NaN, then filling NaN with inf after division
batsmen_stats['strike_rate'] = (batsmen_stats['batsman_runs'] / batsmen_stats['no.of_balls'].replace(0, np.nan)) * 100
batsmen_stats['strike_rate'] = batsmen_stats['strike_rate'].fillna(np.inf)

display(batsmen_stats)

batsman
SK Raina        4548
V Kohli         4423
RG Sharma       4207
G Gambhir       4132
DA Warner       4014
                ...
RR Bhatkal         0
M Ashwin           0
Abdur Razzak       0
IC Pandey          0
Sunny Gupta        0
Name: batsman_runs, Length: 461, dtype: int64

          batsman  batsman_runs  no.of_balls
0        SK Raina          4548         3369
1         V Kohli          4423         3494
2       RG Sharma          4207         3274
3       G Gambhir          4132         3433
4       DA Warner          4014         2902
..            ...           ...          ...
456    RR Bhatkal             0            2
457      M Ashwin             0            1
458  Abdur Razzak             0            2
459     IC Pandey             0            2
460   Sunny Gupta             0            1

[461 rows x 3 columns]

batsman         0
batsman_runs    0
no.of_balls     0
dtype: int64

          batsman  batsman_runs  no.of_balls  strike_rate
0        SK Raina          4548         3369   134.995548
1         V Kohli          4423         3494   126.588437
2       RG Sharma          4207         3274   128.497251
3       G Gambhir          4132         3433   120.361200
4       DA Warner          4014         2902   138.318401
..            ...           ...          ...          ...
456    RR Bhatkal             0            2     0.000000
457      M Ashwin             0            1     0.000000
458  Abdur Razzak             0            2     0.000000
459     IC Pandey             0            2     0.000000
460   Sunny Gupta             0            1     0.000000

[461 rows x 4 columns]

In [ ]:
dataset.columns

In [ ]:
import numpy as np
a = np.array([2,3])
b = np.array([4,-1])

print(a@b)