In [18]:
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv('/content/delivery_dataset_cleaned.csv')

1. Inspecting the dataset

In [26]:
# df = df.drop(columns=['Unnamed: 0'])

df['dismissal_kind'] = df['dismissal_kind'].fillna('N/A')
df['fielder'] = df['fielder'].fillna('N/A')

In [33]:
display(df.shape)

(150459, 21)

In [21]:
df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [22]:
display(df.head())

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,not out,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,not out,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,not out,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,not out,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,not out,NaN,NaN

In [28]:
display(df.describe())

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000
mean,318.281964,1.482191,10.142690,3.616500,0.000538,0.037499,0.004885,0.022232,0.004340,0.000066,1.222446,0.069022,1.291468
std,182.955967,0.501768,5.674335,1.807691,0.023196,0.257398,0.114235,0.200105,0.072652,0.018229,1.594515,0.349668,1.583245
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,161.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,319.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,476.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,636.000000,4.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,6.000000,7.000000,7.000000

In [31]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150459 entries, 0 to 150458
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          150459 non-null  int64
 1   inning            150459 non-null  int64
 2   batting_team      150459 non-null  object
 3   bowling_team      150459 non-null  object
 4   over              150459 non-null  int64
 5   ball              150459 non-null  int64
 6   batsman           150459 non-null  object
 7   non_striker       150459 non-null  object
 8   bowler            150459 non-null  object
 9   is_super_over     150459 non-null  int64
 10  wide_runs         150459 non-null  int64
 11  bye_runs          150459 non-null  int64
 12  legbye_runs       150459 non-null  int64
 13  noball_runs       150459 non-null  int64
 14  penalty_runs      150459 non-null  int64
 15  batsman_runs      150459 non-null  int64
 16  extra_runs        150459 non-null  int64
 17  total_runs        150459 non-null  int64
 18  player_dismissed  150459 non-null  object
 19  dismissal_kind    150459 non-null  object
 20  fielder           150459 non-null  object
dtypes: int64(13), object(8)
memory usage: 24.1+ MB

None

In [35]:
display(df.index)

RangeIndex(start=0, stop=150459, step=1)

In [36]:
display(df.describe(include='all'))

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
count,150459.000000,150459.000000,150459,150459,150459.000000,150459.000000,150459,150459,150459,150459.000000,...,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459.000000,150459,150459,150459
unique,NaN,NaN,12,12,NaN,NaN,461,458,356,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,437,10,452
top,NaN,NaN,Mumbai Indians,Mumbai Indians,NaN,NaN,V Kohli,G Gambhir,Harbhajan Singh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not out,N/A,N/A
freq,NaN,NaN,18942,18879,NaN,NaN,3494,3635,2989,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143021,143021,145090
mean,318.281964,1.482191,NaN,NaN,10.142690,3.616500,NaN,NaN,NaN,0.000538,...,0.004885,0.022232,0.004340,0.000066,1.222446,0.069022,1.291468,NaN,NaN,NaN
std,182.955967,0.501768,NaN,NaN,5.674335,1.807691,NaN,NaN,NaN,0.023196,...,0.114235,0.200105,0.072652,0.018229,1.594515,0.349668,1.583245,NaN,NaN,NaN
min,1.000000,1.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
25%,161.000000,1.000000,NaN,NaN,5.000000,2.000000,NaN,NaN,NaN,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
50%,319.000000,1.000000,NaN,NaN,10.000000,4.000000,NaN,NaN,NaN,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,NaN,NaN,NaN
75%,476.000000,2.000000,NaN,NaN,15.000000,5.000000,NaN,NaN,NaN,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,NaN,NaN,NaN
max,636.000000,4.000000,NaN,NaN,20.000000,9.000000,NaN,NaN,NaN,1.000000,...,4.000000,5.000000,5.000000,5.000000,6.000000,7.000000,7.000000,NaN,NaN,NaN

In [42]:
display(df.dtypes)

match_id             int64
inning               int64
batting_team        object
bowling_team        object
over                 int64
ball                 int64
batsman             object
non_striker         object
bowler              object
is_super_over        int64
wide_runs            int64
bye_runs             int64
legbye_runs          int64
noball_runs          int64
penalty_runs         int64
batsman_runs         int64
extra_runs           int64
total_runs           int64
player_dismissed    object
dismissal_kind      object
fielder             object
dtype: object

In [43]:
display(df.memory_usage(deep=True))

Index                    132
match_id             1203672
inning               1203672
batting_team        10019527
bowling_team        10023663
over                 1203672
ball                 1203672
batsman              8785246
non_striker          8785382
bowler               8797137
is_super_over        1203672
wide_runs            1203672
bye_runs             1203672
legbye_runs          1203672
noball_runs          1203672
penalty_runs         1203672
batsman_runs         1203672
extra_runs           1203672
total_runs           1203672
player_dismissed     8443747
dismissal_kind       7848241
fielder              7858916
dtype: int64

In [44]:
display(df.nunique())

match_id            636
inning                4
batting_team         12
bowling_team         12
over                 20
ball                  9
batsman             461
non_striker         458
bowler              356
is_super_over         2
wide_runs             6
bye_runs              5
legbye_runs           6
noball_runs           5
penalty_runs          2
batsman_runs          7
extra_runs            7
total_runs            8
player_dismissed    437
dismissal_kind       10
fielder             452
dtype: int64

In [46]:
display(df.isna().mean())
display(df.isna().mean()*100)

match_id            0.0
inning              0.0
batting_team        0.0
bowling_team        0.0
over                0.0
ball                0.0
batsman             0.0
non_striker         0.0
bowler              0.0
is_super_over       0.0
wide_runs           0.0
bye_runs            0.0
legbye_runs         0.0
noball_runs         0.0
penalty_runs        0.0
batsman_runs        0.0
extra_runs          0.0
total_runs          0.0
player_dismissed    0.0
dismissal_kind      0.0
fielder             0.0
dtype: float64

match_id            0.0
inning              0.0
batting_team        0.0
bowling_team        0.0
over                0.0
ball                0.0
batsman             0.0
non_striker         0.0
bowler              0.0
is_super_over       0.0
wide_runs           0.0
bye_runs            0.0
legbye_runs         0.0
noball_runs         0.0
penalty_runs        0.0
batsman_runs        0.0
extra_runs          0.0
total_runs          0.0
player_dismissed    0.0
dismissal_kind      0.0
fielder             0.0
dtype: float64

In [47]:
display(df.duplicated().sum())

np.int64(0)

2. Boolean Filtering

In [48]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,not out,N/A,N/A
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,not out,N/A,N/A

In [53]:
#CSK matches


display(df[(df['batting_team'] == 'Chennai Super Kings') | (df['bowling_team'] == 'Chennai Super Kings')])

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
14087,61,1,Chennai Super Kings,Punjab Kings,1,1,PA Patel,ML Hayden,B Lee,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
14088,61,1,Chennai Super Kings,Punjab Kings,1,2,PA Patel,ML Hayden,B Lee,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
14089,61,1,Chennai Super Kings,Punjab Kings,1,3,PA Patel,ML Hayden,B Lee,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
14090,61,1,Chennai Super Kings,Punjab Kings,1,4,ML Hayden,PA Patel,B Lee,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
14091,61,1,Chennai Super Kings,Punjab Kings,1,5,ML Hayden,PA Patel,B Lee,0,...,0,0,0,0,4,0,4,not out,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136358,576,2,Chennai Super Kings,Mumbai Indians,20,2,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,2,0,2,not out,N/A,N/A
136359,576,2,Chennai Super Kings,Mumbai Indians,20,3,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,6,0,6,not out,N/A,N/A
136360,576,2,Chennai Super Kings,Mumbai Indians,20,4,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,2,0,2,not out,N/A,N/A
136361,576,2,Chennai Super Kings,Mumbai Indians,20,5,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,6,0,6,not out,N/A,N/A
136362,576,2,Chennai Super Kings,Mumbai Indians,20,6,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,4,0,4,not out,N/A,N/A

In [56]:
# MI matches
display(df[(df['batting_team'] == 'Mumbai Indians') | (df['bowling_team'] == 'Mumbai Indians')])

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
248,2,1,Mumbai Indians,Rising Pune Supergiant,1,1,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,1,1,not out,N/A,N/A
249,2,1,Mumbai Indians,Rising Pune Supergiant,1,2,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
250,2,1,Mumbai Indians,Rising Pune Supergiant,1,3,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
251,2,1,Mumbai Indians,Rising Pune Supergiant,1,4,JC Buttler,PA Patel,AB Dinda,0,...,0,0,0,0,5,0,5,not out,N/A,N/A
252,2,1,Mumbai Indians,Rising Pune Supergiant,1,5,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,4,0,4,not out,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148995,630,2,Gujarat Lions,Mumbai Indians,18,1,DR Smith,RA Jadeja,MJ McClenaghan,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
148996,630,2,Gujarat Lions,Mumbai Indians,18,2,RA Jadeja,DR Smith,MJ McClenaghan,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
148997,630,2,Gujarat Lions,Mumbai Indians,18,3,RA Jadeja,DR Smith,MJ McClenaghan,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
148998,630,2,Gujarat Lions,Mumbai Indians,18,4,RA Jadeja,DR Smith,MJ McClenaghan,0,...,0,0,0,0,4,0,4,not out,N/A,N/A
148999,630,2,Gujarat Lions,Mumbai Indians,18,5,RA Jadeja,DR Smith,MJ McClenaghan,0,...,0,0,0,0,1,0,1,not out,N/A,N/A

In [58]:
display(df.query("bowling_team == 'Chennai Super Kings' or batting_team == 'Chennai Super Kings'"))

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
14087,61,1,Chennai Super Kings,Punjab Kings,1,1,PA Patel,ML Hayden,B Lee,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
14088,61,1,Chennai Super Kings,Punjab Kings,1,2,PA Patel,ML Hayden,B Lee,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
14089,61,1,Chennai Super Kings,Punjab Kings,1,3,PA Patel,ML Hayden,B Lee,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
14090,61,1,Chennai Super Kings,Punjab Kings,1,4,ML Hayden,PA Patel,B Lee,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
14091,61,1,Chennai Super Kings,Punjab Kings,1,5,ML Hayden,PA Patel,B Lee,0,...,0,0,0,0,4,0,4,not out,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136358,576,2,Chennai Super Kings,Mumbai Indians,20,2,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,2,0,2,not out,N/A,N/A
136359,576,2,Chennai Super Kings,Mumbai Indians,20,3,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,6,0,6,not out,N/A,N/A
136360,576,2,Chennai Super Kings,Mumbai Indians,20,4,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,2,0,2,not out,N/A,N/A
136361,576,2,Chennai Super Kings,Mumbai Indians,20,5,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,6,0,6,not out,N/A,N/A
136362,576,2,Chennai Super Kings,Mumbai Indians,20,6,MM Sharma,RA Jadeja,R Vinay Kumar,0,...,0,0,0,0,4,0,4,not out,N/A,N/A

In [63]:
df.query("(batting_team == 'Chennai Super Kings' or bowling_team == 'Chennai Super Kings') and batsman == 'RA Jadeja'")

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
27330,117,2,Rajasthan Royals,Chennai Super Kings,18,1,RA Jadeja,YK Pathan,JA Morkel,0,...,0,0,0,0,0,0,0,RA Jadeja,caught,CK Kapugedera
31892,137,2,Rajasthan Royals,Chennai Super Kings,6,4,RA Jadeja,RJ Quiney,JA Morkel,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
31895,137,2,Rajasthan Royals,Chennai Super Kings,7,1,RA Jadeja,RJ Quiney,M Muralitharan,0,...,0,0,0,0,0,0,0,not out,N/A,N/A
31896,137,2,Rajasthan Royals,Chennai Super Kings,7,2,RA Jadeja,RJ Quiney,M Muralitharan,0,...,0,0,0,0,2,0,2,not out,N/A,N/A
31897,137,2,Rajasthan Royals,Chennai Super Kings,7,3,RA Jadeja,RJ Quiney,M Muralitharan,0,...,0,1,0,0,0,1,1,not out,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136344,576,2,Chennai Super Kings,Mumbai Indians,18,1,RA Jadeja,P Negi,SL Malinga,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
136349,576,2,Chennai Super Kings,Mumbai Indians,18,6,RA Jadeja,R Ashwin,SL Malinga,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
136353,576,2,Chennai Super Kings,Mumbai Indians,19,3,RA Jadeja,MM Sharma,MJ McClenaghan,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
136355,576,2,Chennai Super Kings,Mumbai Indians,19,5,RA Jadeja,MM Sharma,MJ McClenaghan,0,...,0,0,0,0,1,0,1,not out,N/A,N/A
136357,576,2,Chennai Super Kings,Mumbai Indians,20,1,RA Jadeja,MM Sharma,R Vinay Kumar,0,...,0,0,0,0,1,0,1,not out,N/A,N/A