In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))

In [2]:
from src.data import load_csv
from src.models import SimpleLinearRegression

In [3]:
slr = SimpleLinearRegression()

In [6]:
df = load_csv('../data/hour.csv')

In [7]:
df.head()

      dteday  season  yr  mnth  hr  ...  temp   atemp   hum  windspeed  cnt
0 2011-01-01       1   0     1   0  ...  0.24  0.2879  0.81        0.0   16
1 2011-01-01       1   0     1   1  ...  0.22  0.2727  0.80        0.0   40
2 2011-01-01       1   0     1   2  ...  0.22  0.2727  0.80        0.0   32
3 2011-01-01       1   0     1   3  ...  0.24  0.2879  0.75        0.0   13
4 2011-01-01       1   0     1   4  ...  0.24  0.2879  0.75        0.0    1

[5 rows x 14 columns]

In [8]:
df.sort_values(by=['dteday', 'hr'])

          dteday  season  yr  mnth  hr  ...  temp   atemp   hum  windspeed  cnt
0     2011-01-01       1   0     1   0  ...  0.24  0.2879  0.81     0.0000   16
1     2011-01-01       1   0     1   1  ...  0.22  0.2727  0.80     0.0000   40
2     2011-01-01       1   0     1   2  ...  0.22  0.2727  0.80     0.0000   32
3     2011-01-01       1   0     1   3  ...  0.24  0.2879  0.75     0.0000   13
4     2011-01-01       1   0     1   4  ...  0.24  0.2879  0.75     0.0000    1
...          ...     ...  ..   ...  ..  ...   ...     ...   ...        ...  ...
17374 2012-12-31       1   1    12  19  ...  0.26  0.2576  0.60     0.1642  119
17375 2012-12-31       1   1    12  20  ...  0.26  0.2576  0.60     0.1642   89
17376 2012-12-31       1   1    12  21  ...  0.26  0.2576  0.60     0.1642   90
17377 2012-12-31       1   1    12  22  ...  0.26  0.2727  0.56     0.1343   61
17378 2012-12-31       1   1    12  23  ...  0.26  0.2727  0.65     0.1343   49

[17379 rows x 14 columns]